services:
  db:
    image: postgres:15
    container_name: tisc-db
    environment:
      POSTGRES_USER: tisc_user
      POSTGRES_PASSWORD: qaywsxedc
      POSTGRES_DB: tisc_db
    ports:
      - "5433:5432"
    networks:
      - tisc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tisc_user -d tisc_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: tisc-app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - tisc-network
    environment:
      - DATABASE_URL=postgresql://tisc_user:qaywsxedc@db:5432/tisc_db
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - AUTH_SECRET=${AUTH_SECRET}
    command: >
      sh -c "
      bun install &&
      bun x prisma generate &&
      bun x prisma db push &&
      bun dev
      "

  test:
    image: cypress/included:13.15.0
    container_name: tisc_test
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./:/opt/app
    working_dir: /opt/app
    networks:
      - tisc-network
    environment:
      - CYPRESS_baseUrl=http://app:3000

networks:
  tisc-network:
    driver: bridge